services:
  db:
    image: postgres
    container_name: container-postgres
    restart: always
    environment:
      POSTGRES_USER: maislocacoes
      POSTGRES_PASSWORD: admin
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-maislocacoes
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  volume_postgresql_maislocacoes: