services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ""
      POSTGRES_USER: maislocacoes
      POSTGRES_PASSWORD: admin
    volumes:
      - data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maislocacoes
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    logging:
      driver: "local"
      options:
        max-size: "1000m"
        max-file: "5"
      path: /root/container.log

volumes:
  data: