services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: maislocacoes
      POSTGRES_PASSWORD: admin
    volumes:
      - data:/var/lib/postgresql/data
      - /root/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maislocacoes
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  data: